language: cpp
compiler: gcc

# following http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env: COMPILER=g++-5

# 
before-install:
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh

script:
  - mkdir ../root_build
  - cd ../root_build
  - cmake ../root -DCMAKE_CXX_COMPILER=$COMPILER -Droofit=ON -Dtesting=ON -Droottest=ON -Dminuit2=ON
  - make -j4
