language: cpp
compiler: gcc

# caching of the build dir (which is large, so large timeout (3 minute default))
cache:
  timeout: 1000
  directories:
  - ../root_build

# following http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.9
    packages:
      - ninja-build
      - g++-5
      - libxpm-dev
      - libgsl0-dev
      - libfftw3-dev
      - libafterimage-dev
      - libftgl-dev
      - libgl2ps-dev
      - libglew-dev
      - liblzma-dev
#      - llvm-3.9-dev
env: COMPILER=g++-5

# following http://stackoverflow.com/a/33203355/1199693 and https://github.com/Microsoft/GSL/blob/master/.travis.yml
before_install:
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir -p "${DEPS_DIR}"
install:
  - |
    cd "${DEPS_DIR}"
    if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    fi
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
  - cd "${TRAVIS_BUILD_DIR}"/.. && git clone http://root.cern.ch/git/roottest.git
  - mkdir -p "${TRAVIS_BUILD_DIR}"/../root_build

script:
  - cd "${TRAVIS_BUILD_DIR}"/../root_build
  - |
    if [[ ! -f CMakeCache.txt ]]; then
      cmake ../root -DCMAKE_CXX_COMPILER=$COMPILER -Droofit=ON -Dtesting=ON -Droottest=ON -Dminuit2=ON -Dbuiltin_afterimage=OFF -Dbuiltin_ftgl=OFF -Dbuiltin_glew=OFF -Dccache=ON # -Dbuiltin_llvm=OFF
    fi
  - make -j6 # VERBOSE=1 # don't do verbose right away, will slow it down too much, won't reach caching phase!
#  - |
#    if [[ -f build_cache.tar ]]; then
#      tar xf build_cache.tar
#      rm build_cache.tar
#    else
#      cmake -G Ninja ../root -DCMAKE_CXX_COMPILER=$COMPILER -Droofit=ON -Dtesting=ON -Droottest=ON -Dminuit2=ON -Dbuiltin_afterimage=OFF -Dbuiltin_ftgl=OFF -Dbuiltin_glew=OFF -Dccache=ON # -Dbuiltin_llvm=OFF
#    fi
#  - ninja -j4

# tarring the build directory myself to preserve timestamps, which apparently doesn't work with travis cacher itself
#before_cache:
#  - |
#    cd "${TRAVIS_BUILD_DIR}"/../root_build
#    tar -cf ../build_cache.tar --atime-preserve *
#    rm *
#    mv ../build_cache.tar .
