# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install -y fftw3 gfortran gcc-8

- task: CMake@1
  inputs:
    workingDirectory: 'build-cmake-debug'
    cmakeArgs: '-Droofit=ON -Dminuit2=ON -DLLVM_BUILD_TYPE=Debug -Dtesting=ON'
